### ISSUE TITLE
Fails with Catalyst 5.90082 and 83

### ISSUE THREAD

**Issue by andk** [chiselwright/catalyst-plugin-errorcatcher#3]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/b87e4ea4-a0fe-11e4-bc88-73358971dd2f

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by timbunce** [comment]
I just hit this.

**Comment by timbunce** [comment]
Looks like the only failing tests are using regex to check the formatted layout of the parameters.
I've submitted a PR that disables them. I'm sorry I don't have time to dig deeper.
